package me.hahahah.pojo;

import java.util.Date;
import java.util.Objects;

public class Skill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.id
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.pre_id
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    private Integer preId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.skill_name
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    private String skillName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.max_grade
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    private Integer maxGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.status
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.create_time
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.update_time
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public Skill(Integer id, Integer preId, String skillName, Integer maxGrade, Long status, Date createTime, Date updateTime) {
        this.id = id;
        this.preId = preId;
        this.skillName = skillName;
        this.maxGrade = maxGrade;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public Skill() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.id
     *
     * @return the value of allskill.id
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.id
     *
     * @param id the value for allskill.id
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.pre_id
     *
     * @return the value of allskill.pre_id
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public Integer getPreId() {
        return preId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.pre_id
     *
     * @param preId the value for allskill.pre_id
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public void setPreId(Integer preId) {
        this.preId = preId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.skill_name
     *
     * @return the value of allskill.skill_name
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public String getSkillName() {
        return skillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.skill_name
     *
     * @param skillName the value for allskill.skill_name
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public void setSkillName(String skillName) {
        this.skillName = skillName == null ? null : skillName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.max_grade
     *
     * @return the value of allskill.max_grade
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public Integer getMaxGrade() {
        return maxGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.max_grade
     *
     * @param maxGrade the value for allskill.max_grade
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public void setMaxGrade(Integer maxGrade) {
        this.maxGrade = maxGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.status
     *
     * @return the value of allskill.status
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.status
     *
     * @param status the value for allskill.status
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.create_time
     *
     * @return the value of allskill.create_time
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.create_time
     *
     * @param createTime the value for allskill.create_time
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.update_time
     *
     * @return the value of allskill.update_time
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.update_time
     *
     * @param updateTime the value for allskill.update_time
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Skill skill = (Skill) o;
        return Objects.equals(id, skill.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}