package me.hahahah.pojo;

import java.util.Date;

public class SkillByUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.user_id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.skill_id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    private Integer skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.grade
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.create_time
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_skill.update_time
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public SkillByUser(Integer id, Integer userId, Integer skillId, Integer grade, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.skillId = skillId;
        this.grade = grade;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_skill
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public SkillByUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.id
     *
     * @return the value of user_skill.id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.id
     *
     * @param id the value for user_skill.id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.user_id
     *
     * @return the value of user_skill.user_id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.user_id
     *
     * @param userId the value for user_skill.user_id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.skill_id
     *
     * @return the value of user_skill.skill_id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public Integer getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.skill_id
     *
     * @param skillId the value for user_skill.skill_id
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.grade
     *
     * @return the value of user_skill.grade
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.grade
     *
     * @param grade the value for user_skill.grade
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.create_time
     *
     * @return the value of user_skill.create_time
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.create_time
     *
     * @param createTime the value for user_skill.create_time
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_skill.update_time
     *
     * @return the value of user_skill.update_time
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_skill.update_time
     *
     * @param updateTime the value for user_skill.update_time
     *
     * @mbggenerated Sat Jan 19 11:39:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}