package me.hahahah.pojo;

import java.util.Date;

public class skills {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.user_id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.skill_name
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private String skillName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.grade
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.create_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allskill.update_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public skills(Integer id, Integer userId, String skillName, Integer grade, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.skillName = skillName;
        this.grade = grade;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public skills() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.id
     *
     * @return the value of allskill.id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.id
     *
     * @param id the value for allskill.id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.user_id
     *
     * @return the value of allskill.user_id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.user_id
     *
     * @param userId the value for allskill.user_id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.skill_name
     *
     * @return the value of allskill.skill_name
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public String getSkillName() {
        return skillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.skill_name
     *
     * @param skillName the value for allskill.skill_name
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setSkillName(String skillName) {
        this.skillName = skillName == null ? null : skillName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.grade
     *
     * @return the value of allskill.grade
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.grade
     *
     * @param grade the value for allskill.grade
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.create_time
     *
     * @return the value of allskill.create_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.create_time
     *
     * @param createTime the value for allskill.create_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allskill.update_time
     *
     * @return the value of allskill.update_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allskill.update_time
     *
     * @param updateTime the value for allskill.update_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}