package me.hahahah.pojo;

import java.util.Date;

public class user {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_user.id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_user.username
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_user.password
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_user.create_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_user.update_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_user
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public user(Integer id, String username, String password, Date createTime, Date updateTime) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_user
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public user() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_user.id
     *
     * @return the value of skill_user.id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_user.id
     *
     * @param id the value for skill_user.id
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_user.username
     *
     * @return the value of skill_user.username
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_user.username
     *
     * @param username the value for skill_user.username
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_user.password
     *
     * @return the value of skill_user.password
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_user.password
     *
     * @param password the value for skill_user.password
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_user.create_time
     *
     * @return the value of skill_user.create_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_user.create_time
     *
     * @param createTime the value for skill_user.create_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_user.update_time
     *
     * @return the value of skill_user.update_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_user.update_time
     *
     * @param updateTime the value for skill_user.update_time
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}