package me.hahahah.dao;

import me.hahahah.pojo.Skill;

import java.util.List;

public interface SkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    int insert(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    int insertSelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    Skill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    int updateByPrimaryKeySelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allskill
     *
     * @mbggenerated Sun Jan 06 14:21:38 CST 2019
     */
    int updateByPrimaryKey(Skill record);

    int checkSkillName(String skillName);

    List<Skill> selectSkillChildrenByPreId(Integer preId);

}