package me.hahahah.dao;

import me.hahahah.pojo.user;

public interface userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_user
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_user
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_user
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    int insertSelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_user
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    user selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_user
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    int updateByPrimaryKeySelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill_user
     *
     * @mbggenerated Wed Jan 02 21:20:24 CST 2019
     */
    int updateByPrimaryKey(user record);
}